Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:
    
  Inventory:
    
    make:
      name: Make|Makers
      page: true
      components:
        list:
        show:
        form:
    
    model:
      name: Model|Models
      page: true
      components:
        list:
        show:
        form:
    
    trims:
      name: Trim|Trims
      page: true
      components:
        list:
        show:
        form:
    
    car:
      name: Car|Cars
      page: true
      components:
        list:
        show:
        form:
  
  Blog:
    
    category:
      name: Category|Categories
      components:
        list:
        show:
    
    article:
      name: Article|Articles
      page: true
      components:
        list:
        show:
        form: