<?php

/**
 * Trim
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diem-dealr
 * @subpackage model
 * @author     Rafix
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Trim extends BaseTrim
{

}