<?php

/**
 * TrimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrimTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trim');
    }
}