<?php

/**
 * TrimsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrimsTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrimsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trims');
    }
}