generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Article
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: article
    with_doctrine_route: false
    i18n_catalogue: dm
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - image
          - category_id
          - created_by
          - updated_by
          - content
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - is_active
          - category_id
          - content
          - image
          - created_at
          - updated_at
          - created_by
          - updated_by
      form:
        display:
          NONE: [title, is_active, category_id, tags]
          Image: [image_form, image_view]
          Content: [content]
          Authors: [created_by, updated_by]
        class: ArticleAdminForm
        fields: {  }
      edit: ~
      new: ~
